SELECT * FROM SCOTT.CUST

SELECT COUNT(1) FROM ALL_OBJECTS WHERE OBJECT_NAME='CUST'--WHERE OWNER='SYS'

SELECT OBJECT_NAME, (SYS-APPS)  FROM  ALL_TABLES


SELECT * FROM ALL_OBJECTS WHERE OBJECT_NAME ='CUST'

DESC SYS.


SELECT COUNT(*) FROM USER_TABLES;

select * from usr